### ISSUE TITLE
Arrange the solution

### ISSUE THREAD

**Issue by sassi67** [sassi67/MyStack#1]
- [x] Clone this project and create a new branch **b_001**
- [x] Create a C# solution from a Console project (.Net Core 5, 6 or 7: choose one of these). Call it **MyStack**. 
- [x] Add a MSTest project inside MyStack and call it **MyStackTest**.
- [x] Create a new class **MyMath** with a static method **int Add( int a, int b)**
- [x] Create a new test class **MyMathTest** with some tests with Add
- [x] Create a .gitignore to exclude all the intermediate files and executables
- [x] Commit everything
- [x] Push this project
- [x] Create a pool request

Hint: https://learn.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2022

**Important**: do not use top-level statements

**Comment by AlbertoSacilotto** [comment]
Non ho diritti per pushare
